services:
  db:
    image: postgres:17.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "test"

  identity:
    image: quay.io/keycloak/keycloak:26.1.2
    ports:
      - "8081:8081"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: ["start-dev", "--http-port=8081"]