services:
  db:
    image: postgres:17.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "test"
  oauth2:
    image: quay.io/keycloak/keycloak:26.1.0
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command:
      - start-dev
    ports:
      - "8080:8080"